### ISSUE TITLE
I test the give 6000.pth model on the ECSSD dataset, Fmeasure are 0.7323. I trained myself get the results 0.933. Can you check the 6000.pth is the right model?

### ISSUE THREAD

**Issue by XuecaiHu** [zijundeng/R3Net#2]
I test the give 6000.pth model on the ECSSD dataset, Fmeasure are 0.7323. I trained myself get the results 0.933. Can you check the 6000.pth is the right model?

**Comment by zijundeng** [comment]
Hi Xuecai,
I checked the 6000.pth just now and it's OK.
Best regards
